# Generated by Django 5.2.7 on 2025-10-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(default='xyz', max_length=250),
        ),
    ]
